### ISSUE TITLE
CUDA 11

### ISSUE THREAD

**Issue by joehoeller** [datamachines/cuda_tensorflow_opencv#10]
Do you have CUDA 11 support avail?

**Comment by mmartial** [comment]
Yes, this is planned, no release date out just yet.

The last time I investigated this (Oct 2020), Tensorflow or OpenCV did not appear to yet be fully CUDA11 compatible.
Also, this will have the side effect of changing the base container for the build (ubuntu 20.04 based).

**Comment by mmartial** [comment]
A quick follow up that there should be a new release soon (if I can finish the rest of the steps, hopefully Today) with CUDA11 support.

**Comment by joehoeller** [comment]
Awesome - thank you!!

**Comment by mmartial** [comment]
It did take me less extra time than I expected, the latest containers are available at this point. 
You should see if the releases at https://hub.docker.com/r/datamachines/cudnn_tensorflow_opencv work for your needs.
I will close this issue at this point.
