### ISSUE TITLE
Docker build fail for Jetson Nano 20210218

### ISSUE THREAD

**Issue by lha-s** [datamachines/cuda_tensorflow_opencv#17]
Hello,

My docker build fail at step 27/41
```Step 27/41 : RUN mkdir -p /usr/local/src/torchvision   && wget -q --no-check-certificate https://github.com/pytorch/vision/archive/v0.8.2.tar.gz -O - | tar --strip-components=1 -xz -C /usr/local/src/torchvision   && cd /usr/local/src/torchvision   && python3 setup.py install    && rm -rf /root/.cache/pip /usr/local/src/torchvision
 ---> Running in f4cf6fcad4d7
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
The command '/bin/sh -c mkdir -p /usr/local/src/torchvision   && wget -q --no-check-certificate https://github.com/pytorch/vision/archive/v0.8.2.tar.gz -O - | tar --strip-components=1 -xz -C /usr/local/src/torchvision   && cd /usr/local/src/torchvision   && python3 setup.py install    && rm -rf /root/.cache/pip /usr/local/src/torchvision' returned a non-zero code: 1
Makefile:95: recipe for target 'actual_build' failed
make[2]: *** [actual_build] Error 1
make[2]: Leaving directory '/home/lisalink/cuda_tensorflow_opencv/JetsonNano'
Makefile:68: recipe for target 'build_prep' failed
make[1]: *** [build_prep] Error 2
make[1]: Leaving directory '/home/lisalink/cuda_tensorflow_opencv/JetsonNano'
Makefile:65: recipe for target 'jetsonnano-cuda_tensorflow_opencv-10.2_2.3_4.5.1' failed
make: *** [jetsonnano-cuda_tensorflow_opencv-10.2_2.3_4.5.1] Error 2
```
I installed Jetpack 4.5.0 without doing anything else. Not even apt update or  apt upgrade
Please can you help with that issue ?

**Comment by mmartial** [comment]
Interesting, the error message `OSError: libcurand.so.10: cannot open shared object file: No such file or directory` is about a mount from the host OS to the internal OS, which means that there is a mismatch on the Nano's version of CUDA and the one used within container.
This link addresses this https://stackoverflow.com/questions/64482976/oserror-libcurand-so-10-cannot-open-shared-object-file-no-such-file-or-direct

Can you please try to see if you can use the pre-built container, see https://github.com/datamachines/cuda_tensorflow_opencv/blob/master/Builds-DockerHub.md#3-jetsonnano-cuda_tensorflow_opencv

**Comment by lha-s** [comment]
I tried the same pre-built version also and i can run it.
i used:
`docker pull datamachines/jetsonnano-cuda_tensorflow_opencv:10.2_2.3_4.5.1-20210218`
`CONTAINER_ID=datamachines/jetsonnano-cuda_tensorflow_opencv:10.2_2.3_4.5.1-20210218 ./runDocker.sh`
_The exemple you use in the Readme [here](https://github.com/datamachines/cuda_tensorflow_opencv/#5-using-the-container-images) is using a hyphen and i had to change it to a colon_

I'll try to `make` again with the suggested solution later, thank you for you help.

The main issue for me now is to make it work with Yolov4_Tiny. 
Maybe you have some advices for me ?
Do i have to use `docker exec -it <NAME> bash` to put my Yolov4_Tiny inside the container or to `make` and add to my image my pre-configured Yolov4_Tiny ?

**Comment by mmartial** [comment]
is that https://github.com/datamachines/cuda_tensorflow_opencv/tree/master/JetsonNano#2-a-note-on-alexyeyabdarknet with `tiny` weights?

**Comment by mmartial** [comment]
To answer your previous question, I would `docker run -it <NAME> /bin/bash` to get the install steps documented, generate a new `Dockerfile` using `FROM <NAME>` and build it and then simply use that new container going forward.

**Comment by lha-s** [comment]
Yes it's the Tiny version.
Thank you.

**Comment by mmartial** [comment]
Did the [link](https://github.com/datamachines/cuda_tensorflow_opencv/tree/master/JetsonNano#2-a-note-on-alexyeyabdarknet) to building help?

**Comment by lha-s** [comment]
yes, thank you
