### ISSUE TITLE
1.15.2 images are built without tensorflow-gpu (irrespective of CUDA or CUDNN)

### ISSUE THREAD

**Issue by eric-eric-eric** [datamachines/cuda_tensorflow_opencv#3]
Looks like all 1.15.2 images are built with tensorflow and not tensorflow-gpu.

In Makefile:
`@$(eval CTO_TENSORFLOW_PYTHON=$(shell if [ "A${CTO_TMP}" == "A${STABLE_TF1}" ]; then echo "tensorflow==${STABLE_TF1}"; else if [ ${CTO_SC} == 1 ]; then echo "tensorflow==${STABLE_TF2}"; else echo "tensorflow-gpu==${STABLE_TF2}"; fi; fi))`

Is this intentional?

**Comment by mmartial** [comment]
It was but your question makes me wonder if I misread the https://www.tensorflow.org/install/gpu details on 1.15 having gpu integrated. I need to check.

**Comment by mmartial** [comment]
Reading the following https://github.com/tensorflow/tensorflow/issues/36476 
I might need to adapt indeed and integrate a test to check it as well

**Comment by mmartial** [comment]
It appears that below 2.0 I will still need to select the `-gpu` pip package, so I am looking at fixing this.

**Comment by eric-eric-eric** [comment]
👍 thanks!

**Comment by mmartial** [comment]
This had me re-evaluate how TF is integrated and the latest code in `develop-linux` builds TF from source at this point. I will post new images when I have confirmed full functionality.

**Comment by mmartial** [comment]
Pushing `20200615` release shortly which will bypass the `-gpu` component entirely.
Closing this issue.
