### ISSUE TITLE
DockerFiles

### ISSUE THREAD

**Issue by estebanroblesluna** [datamachines/cuda_tensorflow_opencv#36]
Hi,
Thanks for providing the builds in hub.docker.
I'm looking to make some changes to one of the images to include NVDEC in the opencv build and be able to use cv2.cudacodec.createVideoReader
Are the original DockerFile available somewhere?
Thanks

**Comment by mmartial** [comment]
Unfortunately, it is a little bit complicated to get the `Dockerfile` directly.
The `Makefile` replace environment variables at build time.
If you look within the `BuildInfo` directory for a given version of the build and inside the `.txt` files there, you will see the `docker build [...] -f ubuntu20.04/Dockerfile` line that was used.
You can edit the `Dockerfile` and either replace the `ARG` values with the ones from the command line (ex: replace `ARG CTO_FROM` by `ARG CTO_FROM=ubuntu:22.04`) or run the `docker build` line as it was run at the time.

Check https://github.com/datamachines/cuda_tensorflow_opencv/blob/master/BuildInfo/cudnn_tensorflow_opencv-11.6.2_2.9.1_4.6.0-20220815/cudnn_tensorflow_opencv-11.6.2_2.9.1_4.6.0-20220815-OpenCV.txt for example

Hoping this helps

**Comment by estebanroblesluna** [comment]
Got it!
Thanks
