### ISSUE TITLE
Support for the latest version of PyTorch 1.8.0, Tensorflow 2.3.1 and OpenCV 4.5.0

### ISSUE THREAD

**Issue by mexico-johnny** [datamachines/cuda_tensorflow_opencv#6]
@mmartial - Stumbled across your repo and found it to be quite handy! Thanks for putting this together.

We're looking to  create a docker image that contains the latest combinations of:
-Tensorflow 2.3.1
-Cuda 10.1, 10.2, 11.0
-PyTorch 1.7.0 and corresponding versions of torchvision (unsure which version is correct)
- OpenCV 4.5.0

Any chance you could add support for these combinations?

Thanks!

**Comment by mmartial** [comment]
CUDA 11 was not supported by most of the Frameworks, so this one is still in question. 10.2 is the target for now, but yes, I have had to back up a little bit, but the plan is to update with the latest "compatible" versions soon.

Keeping this open until I have had a chance to investigate further.

**Comment by mmartial** [comment]
Please check `20201204` release as it includes most of the requested support (but not CUDA 11).
Closing this for the time being.
