### ISSUE TITLE
do you guys have any plan to build the image with a newer python version? 

### ISSUE THREAD

**Issue by omlomloml** [datamachines/cuda_tensorflow_opencv#7]
3.6.9 is kind of old

**Comment by mmartial** [comment]
The base container we are using was using this version of Python.
New 20.04 base containers are available, so our plan is to investigate their use.

Will follow up here when we have something.

**Comment by mmartial** [comment]
Ubuntu 20.04 containers are only for CUDA 11 based containers, which limits what we can do given that TF and OpenCV did not seem to be 100% compatible with it yet.

We added support for Python 3.7 for TensorFlow 1 builds (3.7 is listed as the max supported version) and Python 3.8 for Tensorflow 2 builds.

This makes use of the [`deadsnakes/ppa`](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) and changes the default `python3`.

**Comment by mmartial** [comment]
Please see `20201204` release to benefit from the above. 
Closing this issue at this point.
