### ISSUE TITLE
Segmentation fault (core dumped) with datamachines/jetsonnano-cuda_tensorflow_opencv:10.0_2.1.0_4.3.0-20200515

### ISSUE THREAD

**Issue by betterprogram** [datamachines/cuda_tensorflow_opencv#8]
With datamachines/jetsonnano-cuda_tensorflow_opencv:10.0_2.1.0_4.3.0-20200515,
"Segmentation fault (core dumped)" was returned after running
/dmc# python3 -c "import cv2; print(cv2.__version__)"

"ImportError: No module named cv2" was returned if running
python -c "import cv2; print(cv2.__version__)"

how these errors can be fixed? thanks.

**Comment by mmartial** [comment]
Which base system are you using on your Nano?
I am going to have to check this further and will follow up.

**Comment by najmehs** [comment]
Thanks for sharing the images and instructions! 
It seems like I have similar problem! I am using the image "10.2_2.3.1_4.5.0-20201204" from cuda_tensorflow_opencv, and when I tried the cuda optimized function of opencv (`cv2.cuda_OpticalFlowDual_TVL1().calc(im1, im2, None)`, I got `Segmentation fault (core dumped)` error! Can you please help? My NVIDIA driver version is `440.33.01`. 
Thank you!

**Comment by mmartial** [comment]
I am unfortunately experiencing the same problem using the latest JetPack (4.5)
I am looking at changing the base container since Nvidia now provides their own pre-built container Tensorflow, see https://ngc.nvidia.com/catalog/containers/nvidia:l4t-tensorflow/tags
Which would just have us need to install and test OpenCV

**Comment by mmartial** [comment]
https://github.com/datamachines/cuda_tensorflow_opencv/releases/tag/20210218 provides a new version (based on JetPack 4.5) that fixes this error and checks at build time for this in the future. New containers in the process of being uploaded.

Closing issue with this release.
